Feature/users
ruslangaifutdinov/fast-company pull request #1
Opened 2022-11-09 19:00 UTC by ruslangaifutdinov

2022-11-09 19:24 UTC, AndreiSachuk requested changes
Дорабатываем

2022-11-09 19:24 UTC, AndreiSachuk commented on src/components/table.jsx
> +  const renderString = () => {
неверно формируется фраза,12 22 102

2022-11-09 19:24 UTC, AndreiSachuk commented on src/components/table.jsx
> +            <button
этот элемент не кнопка, тебе писали в группе

2022-11-09 19:24 UTC, AndreiSachuk commented on src/components/table.jsx
> +        <td key={user.profession.id}>{user.profession.name}</td>
для чего тут ключ?

2022-11-09 19:24 UTC, AndreiSachuk commented on src/components/table.jsx
> +      {users.length !== 0 ? renderTable() : <></>}
users.length && renderTable()

2022-11-12 18:01 UTC, AndreiSachuk reviewed
так получше
открываю решерние автора, посмотри

2022-11-12 18:01 UTC, AndreiSachuk commented on src/components/table.jsx
> +    setUsers((prevState) => prevState.filter((user) => user !== userDelete));
тут бы я конечно смотрел по userId все же, т.к. ссылочный тип данных может дать осечку, когда начнещь работать с сервером

2022-11-12 18:18 UTC, ruslangaifutdinov commented on src/components/table.jsx
> +    setUsers((prevState) => prevState.filter((user) => user !== userDelete));
Исправил на проверку по id

2022-11-12 18:18 UTC, merged