Feature/grouplist
ruslangaifutdinov/fast-company pull request #4
Opened 2022-11-29 10:29 UTC by ruslangaifutdinov

2022-11-30 09:15 UTC, AndreiSachuk requested changes
на платформе написал проблемы

2022-11-30 09:15 UTC, AndreiSachuk commented on src/app/components/users.jsx
> +    users: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
а они разве не required?

2022-12-01 06:50 UTC, ruslangaifutdinov commented on src/app/components/users.jsx
> +    users: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
Ну здесь я просто за автором повторил, так как он в GroupList написал так:
 items: PropTypes.oneOfType([PropTypes.object, PropTypes.array]), но поправил

2022-12-01 08:20 UTC, AndreiSachuk approved these changes

2022-12-05 18:51 UTC, merged